version: '3.7'

services:
  # Service JSON Server personnalisé avec Dockerfile
  jsonserver:
    build: .
    container_name: jsonserver
    ports:
      - "3234:3234"  # Port pour accéder localement en HTTP
    volumes:
      - ./assets/data:/app/assets/data  # Monter le répertoire local des assets
      - ./assets:/app/assets            # Monter le répertoire local des assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jsonserver.rule=Host(`sae-projet-jsonserverv-vvr3q3-1b215e-77-37-120-142.traefik.me`)"
      - "traefik.http.routers.jsonserver.entrypoints=websecure"
      - "traefik.http.routers.jsonserver.tls=true"
      - "traefik.http.routers.jsonserver.tls.certresolver=http"
      - "traefik.http.services.jsonserver.loadbalancer.server.port=3234"

  # Traefik
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--entryPoints.web.address=:8000"
      - "--entryPoints.websecure.address=:8443"
      - "--certificatesResolvers.http.acme.email=marquesjulian2@gmail.com"
      - "--certificatesResolvers.http.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=web"
    ports:
      - "8000:80"   # Port HTTP
      - "8443:443" # Port HTTPS
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - web

networks:
  web:
    external: true
    driver: bridge