version: "3.8"

services:
  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3234"
    networks:
      - mynetwork

  json-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - json-server
    networks:
      - mynetwork
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:80"
    depends_on:
      - json-proxy
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
